name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make setup

    - name: Run pre-commit hooks
      run: make format

    - name: Check for changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Linting or formatting changes detected. Please run 'make format' locally and commit the changes."
          git diff
          exit 1
        fi
